// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Y1k0uFch9KrYBmEJtrr9JRc7Vo-GNPE',
    appId: '1:134800071720:web:431a03a90c1ea29e4fa91d',
    messagingSenderId: '134800071720',
    projectId: 'pathguide-7ae0f',
    authDomain: 'pathguide-7ae0f.firebaseapp.com',
    storageBucket: 'pathguide-7ae0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7ulHEo0nVm_8p3sJHhfkPK_udcqXWogg',
    appId: '1:134800071720:android:59ef592df133e7a74fa91d',
    messagingSenderId: '134800071720',
    projectId: 'pathguide-7ae0f',
    storageBucket: 'pathguide-7ae0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB811Kvcum5vqPefqN_CSvRmu3qKmt-9AA',
    appId: '1:134800071720:ios:efb3f9c05ee0e72a4fa91d',
    messagingSenderId: '134800071720',
    projectId: 'pathguide-7ae0f',
    storageBucket: 'pathguide-7ae0f.appspot.com',
    iosBundleId: 'com.example.pathguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB811Kvcum5vqPefqN_CSvRmu3qKmt-9AA',
    appId: '1:134800071720:ios:46b060d7502283294fa91d',
    messagingSenderId: '134800071720',
    projectId: 'pathguide-7ae0f',
    storageBucket: 'pathguide-7ae0f.appspot.com',
    iosBundleId: 'com.example.pathguide.RunnerTests',
  );
}
